### ISSUE TITLE
DB Engines and Versions

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud-docs/relational-database-service#27]
Issue on page:        https://github.com/opentelekomcloud-docs/relational-database-service/blob/main/umn/source/introduction/db_instance_description/db_engines_and_versions.rst

Microsoft SQL Server | 2017 SE

The doc page reports latest Version 2017. The doc pages seem to be outdated. Would you please refresh them asap?

Thx

**Comment by lboka** [comment]
Hi Robert,
Sorry for late answer. I see that the issue was fixed and the latest version in doc is now version 2019.
![image](https://github.com/opentelekomcloud-docs/relational-database-service/assets/96316177/9f5c2caa-d879-44fc-9fa3-f61eb5ea8f07)
