### ISSUE TITLE
Supported Plugins - PostgreSQL 15 is missing in the list

### ISSUE THREAD

**Issue by SebastianGode** [opentelekomcloud-docs/relational-database-service#52]
Issue on page:        https://github.com/opentelekomcloud-docs/relational-database-service/blob/main/umn/source/working_with_rds_for_postgresql/plugin_management/supported_plugins.rst

Here the current supported PostgreSQL version 15 from RDS is missing in the table.

**Comment by onszekel** [comment]
Hi @SebastianGode, 
I can actually see the PG15 supported plugins in the table on the HelpCenter.
https://docs.otc.t-systems.com/relational-database-service/umn/working_with_rds_for_postgresql/plugin_management/supported_plugins.html#rds-09-0045

Can you please recheck it again?
We uploaded a new document version on RDS in the recent 2 weeks, so hopefully you should see it know.

**Comment by SebastianGode** [comment]
Thanks @onszekel 
Now the document is updated :)
Issue closed.
